### ISSUE TITLE
After Update to new Release 0.2.0 i get Error  LoginError: Login not possible

### ISSUE THREAD

**Issue by Dimonic2210** [Tom-Hirschberger/MMM-SynologySurveillance#22] opened 2024-04-23 05:55 UTC
Attached the logs.
i already creted a new user with manager authorizations, but the error still occures.

0|mm  | [2024-04-23 07:49:40.813] [LOG]   LoginError: Login not possible
0|mm  | API does not exist
0|mm  |     at /home/pi/MagicMirror/modules/MMM-SynologySurveillance/MySynoSSClient.js:320:47
0|mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|mm  |     at async Class.getInfoOfAllDs (/home/pi/MagicMirror/modules/MMM-SynologySurveillance/node_helper.js:77:34) {
0|mm  |   cause: {
0|mm  |     response: {
0|mm  |       status: 200,
0|mm  |       statusText: 'OK',
0|mm  |       headers: [Object [AxiosHeaders]],
0|mm  |       config: [Object],
0|mm  |       request: [ClientRequest],
0|mm  |       data: [Object]
0|mm  |     },
0|mm  |     returnCode: 102
0|mm  |   }
0|mm  | }

**Comment by Tom-Hirschberger** [comment] 2024-04-23 06:00
Hi,

are you sure you disabled the two-factor-authentication for this user?
If the manager role is not set the error code will be 105 - Privilege Error.
102 indicates that the login is not possible.

23.04.2024 07:56:05 Dimonic2210 ***@***.***>:

**Comment by Dimonic2210** [comment] 2024-04-23 06:26
yes two-factor-authentication is disabled.
But was means "API does not exist" ?

**Comment by Tom-Hirschberger** [comment] 2024-04-23 18:09
That's intetesting. The error happens in the auth api which is a basic api since years.

Can you provide the raw output of the following request...

`http://<THE_IP_OF_YOUR_NAS>:5000/webapi/query.cgi?api=SYNO.API.Info&method=Query&version=1`

**Comment by Dimonic2210** [comment] 2024-04-25 09:16
Hey Tom,
attached the output.
DSM is: 6.2.4-25556 Update 6
Surveillance is: 9.2.0-9289

[out.txt](https://github.com/Tom-Hirschberger/MMM-SynologySurveillance/files/15107248/out.txt)

**Comment by Dimonic2210** [comment] 2024-04-25 09:20
i've tested a downgrade to the previous Version 0.1.4
--> everything runs fine, now error and the cam is shown.

**Comment by Tom-Hirschberger** [comment] 2024-04-25 18:14
Hi and thanks for the info.
Helped me a lot to identify the problem as I do not have any DiskStation with DSM 6.x anymore.

Just released version 0.2.1 of the module which should fix the problem.

**Comment by Tom-Hirschberger** [comment] 2024-09-15 17:45
Hi, as I did not get an feedback till now I assume the problem is fixed with the new implementation.
Feel free to reopen the issue if not.

**Closed by Tom-Hirschberger** 2024-09-15 17:45 UTC
